### ISSUE TITLE
Would you be interested in these changes?

### ISSUE THREAD

**Issue by soupi** [alexmingoia/twain#1]
I've been looking for a very small and thin layer on top of wai and found twain - I think it's pretty great! Thank you for sharing it!

I've tried experimenting with it a bit and made a few changes [in a branch](https://github.com/soupi/twain/commits/experiments). Specifically:

1. I've updated the bounds so it will work with the latest aeson, text and bytestring packages, as well as updating the stackage resolver to the latest nightly (and ghc-9.2.2)
2. I've replaced the package.yaml with a cabal file
3. I've added a `css` response, similar to `html`
4. I've replaced the examples to use lists + `foldr ($)` for routing (so that response code can be written inline without parenthesis)
5. I've added a few tests

Would you be interested in a PR for any of these changes?

Also, I've ported a simple example scotty app that I wrote as a tutorial [to twain](https://github.com/soupi/learn-scotty-bulletin-app/tree/twain), if you're interested, I can probably port the tutorial to twain as well.

Thanks!

**Comment by alexmingoia** [comment]
That would be appreciated. Thank you.

**Comment by alexmingoia** [comment]
Thank you so much. Merged and released.

**Comment by soupi** [comment]
Thanks for the merge! I've ported my scotty tutorial for twain as well:
https://gilmi.me/blog/post/2022/04/24/learn-twain-bulletin-app
